### ISSUE TITLE
from layers.Attention import WaveletAttention, FourierAttention, FullAttention

### ISSUE THREAD

**Issue by mieya** [BeBeYourLove/TDformer#1]
I think there is a wrong in the model/TDformer.py.`from layers.Attention import WaveletAttention, FourierAttention, FullAttention`should be change to `from layers.Attention import FourierAttention, FullAttention` and `from layers.MultiWaveletCorrelation import WaveletAttention`

**Comment by BeBeYourLove** [comment]
It's possible to have this error in your code, but just to make the project work, you can fix it anywhere.

**Comment by BeBeYourLove** [comment]
It's possible to have this error in this code, but just to make the project work, you can fix it anywhere.
