### ISSUE TITLE
cannot import name 'WaveletAttention' from 'layers.Attention'

### ISSUE THREAD

**Issue by wzpzzzz** [BeBeYourLove/TDformer#3]
ImportError: cannot import name 'WaveletAttention' from 'layers.Attention' (D:\School\Paper\TDFormer\TDformer-master\layers\Attention.py)大佬能提供一下WaveletAttention部分的代码嘛

**Comment by BeBeYourLove** [comment]
WaveletAttention就在MultiWaveletCorrelation.py这个文件里面，从这个文件里面导入是一样的。

**Comment by wzpzzzz** [comment]
感谢
